Preprocessing adult.data
=====================

This script helps to preprocess `adult.data` that can be downloaded from the original [UCI Machine Learning repository](https://archive.ics.uci.edu/ml/datasets/adult).

In [1]:
from pathlib import Path

import pandas as pd

**TODO**: please configure `DATA_PATH` and `RAW_ADULT_DATASET_PATH`.

In [2]:
DATA_PATH = Path('/home/nap/Workspace/Privacy-DARC/rmckenna/data')
RAW_ADULT_DATASET_PATH = DATA_PATH / Path('adult.data')
OUTPUT_ADULT_DATASET_PATH = DATA_PATH / Path('adult.csv')

COLUMN_NAMES = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status', 'occupation',
                'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week', 'native-country',
                'salary']

df = pd.read_csv(RAW_ADULT_DATASET_PATH, names=COLUMN_NAMES)
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df.sample(10)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
354,59,?,372020,Bachelors,13,Married-civ-spouse,?,Husband,White,Male,0,0,40,United-States,>50K
9269,36,Private,95336,HS-grad,9,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,45,United-States,>50K
26804,44,Private,33155,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,0,0,45,United-States,<=50K
25884,52,Federal-gov,192065,Some-college,10,Separated,Exec-managerial,Not-in-family,White,Female,0,0,40,United-States,<=50K
2542,25,Private,198632,Some-college,10,Married-spouse-absent,Sales,Not-in-family,White,Male,0,0,50,United-States,<=50K
4592,35,?,117528,Assoc-voc,11,Married-civ-spouse,?,Wife,White,Female,0,0,40,United-States,>50K
26108,34,Private,80058,Prof-school,15,Never-married,Exec-managerial,Own-child,White,Male,0,0,50,United-States,<=50K
3802,22,Private,198148,Some-college,10,Never-married,Adm-clerical,Own-child,White,Male,0,0,50,United-States,<=50K
21888,17,Private,171080,12th,8,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,20,United-States,<=50K
4993,23,Private,74568,Some-college,10,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,40,United-States,<=50K

In [3]:
df.to_csv(OUTPUT_ADULT_DATASET_PATH, index=False)